apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: chaos-ns
spec:
  action: pod-failure
  mode: one
  duration: '30s'
  selector:
    labelSelectors:
      component: selector-component
    namespaces:
      - selector-ns
