apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-network-delay
  namespace: chaos-ns
spec:
  schedule: '*/5 * * * *'
  historyLimit: 1000
  concurrencyPolicy: 'Forbid'
  type: 'NetworkChaos'
  networkChaos:
    action: delay
    mode: one
    selector:
      labelSelectors:
        component: selector-component
      namespaces:
        - selector-ns
    delay:
      latency: '30ms'
      correlation: '100'
      jitter: '0ms'
