apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-failure
  namespace: chaos-ns
spec:
  schedule: '*/5 * * * *'
  historyLimit: 1000
  concurrencyPolicy: 'Forbid'
  type: 'PodChaos'
  podChaos:
    action: pod-failure
    mode: one
    duration: '30s'
    selector:
      labelSelectors:
        component: selector-component
      namespaces:
        - selector-ns
