name: Chaos-Create

on:
  workflow_dispatch:
    inputs:
      exps:
        description: 'Chaos experiments'
        required: true
#      clusterId:
#        description: 'Chaos exp clusterId'
#        required: true
#      expId:
#        description: 'Chaos exp ID'
#        required: true
#      expType:
#        description: 'Chaos exp type'
#        required: true
#      component:
#        description: 'Chaos exp component'
#        required: true
#      properties:
#        description: 'Chaos exp properties'
#        required: true

jobs:
  chaos-pulsar-cluster:
    name: AddChaosExp_${{ github.event.inputs.expId }}
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: ExpId_${{ github.event.inputs.expId }}
        run: |
          echo "exps: ${{ github.event.inputs.exps }}"

#          echo "clusterId: ${{ github.event.inputs.clusterId }}"
#          echo "expId: ${{ github.event.inputs.expId }}"
#          echo "expType: ${{ github.event.inputs.expType }}"
#          echo "component: ${{ github.event.inputs.component }}"
#          echo "properties: ${{ github.event.inputs.properties }}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: BSFishy/pip-action@v1
        with:
          packages: ruamel.yaml

      - name: prepare python components
        run:
          pip install requests

      - name: checkout hello-world repo
        uses: actions/checkout@v2
        with:
          ref: master
          path: hello

      - name: start hook
        run: |
          python ./hello/scripts/test-platform-hook.py chaos_start ${{ github.run_id }} ${{ github.event.inputs.exps }}

      - name: 'install kubectl and helm'
        run: |
          echo 'install kubectl'
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          echo 'install helm'
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - uses: 'google-github-actions/setup-gcloud@master'
        with:
          project_id: 'affable-ray-226821'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/72250869071/locations/global/workloadIdentityPools/chaos-test-identity-pool/providers/github-action'
          service_account: 'sn-chaos-test@affable-ray-226821.iam.gserviceaccount.com'

      # Authenticate using the created credentials file.
      #
      # WARNING: The --cred-file flag is in preview and is subject to change.
      - name: 'gcloud login'
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud config set compute/zone us-east4-b
          echo "------------------- get-credentials -------------------"
          gcloud container clusters get-credentials chaos-tests --region us-central1 --project affable-ray-226821

      - name: checkout chars repo
        uses: actions/checkout@v2
        with:
          repository: gaoran10/charts
          ref: gaoran/use-nio-netty-server-cnx-factory
          path: charts

      - name: deploy chaos exp
        run: |
          python ./hello/scripts/chaos-exp-manager-manually.py ${{ github.event.inputs.exps }}
#          python ./hello/scripts/chaos-exp-manager-manually.py ${{ github.event.inputs.expType }} ${{ github.event.inputs.component }} '${{ github.event.inputs.properties }}' ${{ github.event.inputs.clusterId }}

      - name: create chaos exp finish
        if: ${{ always() ||  success() || cancelled() || failure() }}
        run: |
          python ./hello/scripts/test-platform-hook.py chaos_start_finish ${{ github.run_id }} ${{ github.event.inputs.exps }}
