name: Chaos Cluster Destroy Manually

on:
  workflow_dispatch:
    inputs:
      clusterId:
        description: 'Cluster ID in test platform'
        required: true
      serverHookUrl:
        description: 'The test platform server url'
        required: true

jobs:
  chaos-pulsar-cluster:
    name: DestroyCluster_${{ github.event.inputs.clusterId }}
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: ClusterId_${{ github.event.inputs.clusterId }}
        run: |
          echo "clusterId: ${{ github.event.inputs.clusterId }}"
          echo "serverHookUrl: ${{ github.event.inputs.serverHookUrl }}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: BSFishy/pip-action@v1
        with:
          packages: ruamel.yaml

      - name: prepare python components
        run:
          pip install requests

      - name: checkout hello-world repo
        uses: actions/checkout@v2
        with:
          ref: master
          path: hello

      - name: test link action
        run: |
          python ./hello/scripts/test-platform-hook.py cluster_stop ${{ github.run_id }} ${{ github.event.inputs.clusterId }} '${{ github.event.inputs.serverHookUrl }}'

      - name: 'install kubectl and helm'
        run: |
          echo 'install kubectl'
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          echo 'install helm'
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - uses: 'google-github-actions/setup-gcloud@master'
        with:
          project_id: 'affable-ray-226821'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/72250869071/locations/global/workloadIdentityPools/chaos-test-identity-pool/providers/github-action'
          service_account: 'sn-chaos-test@affable-ray-226821.iam.gserviceaccount.com'

      # Authenticate using the created credentials file.
      #
      # WARNING: The --cred-file flag is in preview and is subject to change.
      - name: 'gcloud login'
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud config set compute/zone us-east4-b
          echo "------------------- get-credentials -------------------"
          gcloud container clusters get-credentials chaos-tests --region us-central1 --project affable-ray-226821

      - name: destroy cluster
        run: |
          helm uninstall 'chaos-pulsar-${{ github.event.inputs.clusterId }}'
          kubectl delete ns 'chaos-${{ github.event.inputs.clusterId }}'
