name: Chaos Cluster Initialization

on:
  issues:
    types: [opened]

jobs:
  chaos-pulsar-cluster:
    name: prepare chaos Pulsar cluster
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: checkout hello-world repo
        uses: actions/checkout@v2
        with:
          ref: master
          path: hello

      - name: check chaos-test label
        env:
          COMMENT_BODY: ${{ github.event.issue.body }}
        run: |
          sh ./hello/scripts/check-chaos-test.sh

      - name: 'install kubectl and helm'
        run: |
          echo 'install kubectl'
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          echo 'install helm'
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: 'affable-ray-226821'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/72250869071/locations/global/workloadIdentityPools/chaos-test-identity-pool/providers/github-action'
          service_account: 'sn-chaos-test@affable-ray-226821.iam.gserviceaccount.com'

      # Authenticate using the created credentials file.
      #
      # WARNING: The --cred-file flag is in preview and is subject to change.
      - name: 'gcloud login'
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud config set compute/zone us-east4-b
          echo "------------------- get-credentials -------------------"
          gcloud container clusters get-credentials chaos-tests --region us-central1 --project affable-ray-226821

      - name: checkout chars repo
        uses: actions/checkout@v2
        with:
          repository: gaoran10/charts
          ref: gaoran/use-nio-netty-server-cnx-factory
          path: charts

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: BSFishy/pip-action@v1
        with:
          packages: ruamel.yaml

      - name: prepare python components
        run:
          pip install requests

      - name: deploy cluster
        env:
          GITHUB_USERNAME: gaoran10
          GITHUB_TOKEN: ${{ secrets.RAN_GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          RUN_ID: ${{ github.run_id }}
          COMMENT_BODY: ${{ github.event.issue.body }}
          TEST_ACTION: create
        run: |
          cd charts
          python ../hello/scripts/chaos-cluster-manager.py
          ./scripts/pulsar/prepare_helm_release.sh -n 'chaos-${{ github.event.issue.number }}' -k 'chaos-pulsar-${{ github.event.issue.number }}' -c
          helm repo add loki https://grafana.github.io/loki/charts
          helm dependency update charts/pulsar-custom
          kubectl label namespace 'chaos-${{ github.event.issue.number }}' istio-injection=enabled
          kubectl create secret generic chaos-pulsar-${{ github.event.issue.number }}-tls-proxy -n 'chaos-${{ github.event.issue.number }}' --from-file=../hello/secure/kop/keystore.jks --from-file=../hello/secure/kop/truststore.jks
          helm install --set initialize=true --set namespace='chaos-${{ github.event.issue.number }}' --values ./charts/pulsar-custom/values.yaml 'chaos-pulsar-${{ github.event.issue.number }}'  ./charts/pulsar-custom/ --debug --wait --timeout 30m
          python ../hello/scripts/chaos-exps-manager.py

      - name: deploy cluster finish
        env:
          GITHUB_USERNAME: gaoran10
          GITHUB_TOKEN: ${{ secrets.RAN_GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          STATUS: ${{ job.status }}
          TEST_ACTION: finish
        if: ${{ always() ||  success() || cancelled() || failure() }}
        run: |
          python ./hello/scripts/chaos-cluster-manager.py
