name: Java CI - pulsar:chaos:test

on:
  issue_comment:
    types: [created]

jobs:
  chaos-test:
    name: run chaos test
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/72250869071/locations/global/workloadIdentityPools/chaos-test-identity-pool/providers/github-action'
          service_account: 'sn-chaos-test@affable-ray-226821.iam.gserviceaccount.com'

      # Example of using the output. The token is usually provided as a Bearer
      # token.
      - id: 'access-secret'
        run: |-
          echo ${{ steps.auth.outputs.access_token }}
          curl https://secretmanager.googleapis.com/v1/projects/my-project/secrets/my-secret/versions/1:access \
            --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: BSFishy/pip-action@v1
        with:
          packages: ruamel.yaml

      - name: prepare python components
        run:
          pip install requests

      - name: checkout hello-world repo
        uses: actions/checkout@v2
        with:
          ref: master
          path: hello

      - name: checkout chaos-test repo
        uses: actions/checkout@v2
        with:
          repository: streamnative/chaos-test
          token: ${{ secrets.RAN_GITHUB_TOKEN }}
          ref: gaoran/adjust-chaos-test-workflow
          path: chaos-test

      - name: chaos test create
        env:
          GITHUB_USERNAME: gaoran10
          GITHUB_TOKEN: ${{ secrets.RAN_GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          RUN_ID: ${{ github.run_id }}
          COMMENT_ID: ${{ github.event.comment.id }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          TEST_ACTION: create
        run: |
          python ./hello/scripts/chaos-test-workflow.py
          cd chaos-test
          mvn -Dtest=SimpleMessagingTest clean test

      - name: chaos test finish
        env:
          GITHUB_USERNAME: gaoran10
          GITHUB_TOKEN: ${{ secrets.RAN_GITHUB_TOKEN }}
          COMMENT_ID: ${{ github.event.comment.id }}
          STATUS: ${{ job.status }}
          TEST_ACTION: finish
        run: |
          python ./hello/scripts/chaos-test-workflow.py

      - name: package reports
        if: failure()
        run: |
          python ./hello/scripts/chaos-test-workflow.py
          rm -rf artifacts
          mkdir artifacts
          find . -type d -name "reports" -exec cp --parents -R {} artifacts/ \;
          zip -r artifacts.zip artifacts

      - uses: actions/upload-artifact@master
        name: upload reports
        if: failure()
        with:
          name: artifacts
          path: artifacts.zip
